### ISSUE TITLE
issues with plato/atari

### ISSUE THREAD

**Issue by mr-atari** [tschak909/platoterm64#14]
For the ESP8266 to become transparent, I need to send one more command to the module.
That is after the module has established connection and data from the server is coming in.
That is a no-go area for me, since plato does not send out CR/LF anymore, nor does control-M/J works.

Plato sends out 1xCR and 2xLF's, not CR/LF, giving errors back from the module. In TTY-mode

Having CAPITOL letters when configuring the connection would be nice, thanks.
Holding SHIFT makes you forget to release it when typing non-letters.
Most modem devices only accept capitol. AT is ok, at is error.

Graphics are drawn faster, but crooked, less nice then the previous build.
Odd pixels (making O->Q) and miss-drawn lines. Errors in backspace/erase and new characters.
Maximum baud-rate 1200 on the old graphic engine else it overflows, new engine can do 2400.
But needs a 256 byte R:buffer and throttled reply to the server.
1200 is safer to use.

plato assumes to be on D1, so when you load it from say D2 it fucks up your disk in D1...

Xon/Xoff does not work. Sending Xoff does not kills data from the server. Blocking Xon from being send does not matter either, data is still poring in.

Missing keys from the atari-layout, they are ignored and thus are not send.
Plato does not let me send $0A / CONTROL-J / LF
When you add LF back to the keyboard-def-table, it would work better for me.
CONTROL-J is not assigned by the plato-keyboard, so.

Inverse characters are not readable.

Data is read 1 character a time from R: , most likely slowing things down.

**Comment by tschak909** [comment]
Hi Sijmen!

Can you try the following build? 
https://github.com/tschak909/platoterm64/releases/tag/PLATOTERM-20181005-ATARI

It adds a pair of keys to switch between TTY and PLATO mode. Hopefully this will work better for you.

Also, since TTY mode now passes keys through as is, if you're holding down caps, they pass through as intended.

the default drive issue is something upstream with cc65. I will try to work around it, but for the mean-time... :)

**Comment by mr-atari** [comment]
select-t and select-p works.

in tty:
*when you press return, plato still sends cr/lf/lf, not cr/lf
*control-j works (lf)
*control-m not. it also sends (lf) while it should be (cr)

**Comment by tschak909** [comment]
https://github.com/tschak909/platoterm64/releases/download/PLATOTERM-20181005-ATARI/plato-20181006-tty-pass-2.atr

You're exhibiting something that I am not seeing in any of my test hardware, so it's very hard for me to try and fix it...but I am trying, nonetheless. 

I will keep going back and forth with you until we get this. 

-Thom

**Comment by mr-atari** [comment]
in altirra/debugger windows:

use 'wb serout' to see last byte send.
or
use '.traceser on' to see all bytes going in/out in the command-window

I can't read c, so that is hopeless too.
In your tty-key_def_table:
keycode $A5 (control-m) should read/send $0D (cr)

Here is the control-piece 
I use in my Tiny Terminal Mode:

DEFTAB

;       Control Characters

	.BYTE      $0C     ;$80 - CTRL-L
	.BYTE      $0A     ;$81 - CTRL-J
	.BYTE      $FF     ;$82 - CTRL-semicolon
	.BYTE      $FF     ;$83 - (invalid) CTRL-F1
	.BYTE      $FF     ;$84 - (invalid) CTRL-F2
	.BYTE      $0B     ;$85 - CTRL-K
	.BYTE      $FF     ;$86 - CTRL-left arrow
	.BYTE      $FF     ;$87 - CTRL-right arrow
	.BYTE      $0F     ;$88 - CTRL-O
	.BYTE      $FF     ;$89 - (invalid)
	.BYTE      $10     ;$8A - CTRL-P
	.BYTE      $15     ;$8B - CTRL-U
	.BYTE      $0D     ;$8C - CTRL-return
	.BYTE      $09     ;$8D - CTRL-I
	.BYTE      $FF     ;$8E - CTRL-up arrow
	.BYTE      $FF     ;$8F - CTRL-down arrow

	.BYTE      $16     ;$90 - CTRL-V
	.BYTE      $FF     ;$91 - (invalid)
	.BYTE      $03     ;$92 - CTRL-C
	.BYTE      $FF     ;$93 - (invalid) CTRL-F3
	.BYTE      $FF     ;$94 - (invalid) CTRL-F4
	.BYTE      $02     ;$95 - CTRL-B
	.BYTE      $18     ;$96 - CTRL-X
	.BYTE      $1A     ;$97 - CTRL-Z
	.BYTE      $FF     ;$98 - CTRL 4	ALT CHAR (invalid)
	.BYTE      $FF     ;$99 - (invalid)
	.BYTE      $FF     ;$9A - CTRL-3	EOL
	.BYTE      $FF     ;$9B - (invalid)
	.BYTE      $1B     ;$9C - CTRL-escape
	.BYTE      $FF     ;$9D - (invalid)
	.BYTE      $FF     ;$9E - CTRL-2	BEL
	.BYTE      $FF     ;$9F - CTRL-1	START/STOP (invalid)

	.BYTE      $00     ;$A0 - CTRL-comma
	.BYTE      $20     ;$A1 - CTRL-space
	.BYTE      $60     ;$A2 - CTRL-period
	.BYTE      $0E     ;$A3 - CTRL-N
	.BYTE      $FF     ;$A4 - (invalid)
	.BYTE      $0D     ;$A5 - CTRL-M
	.BYTE      $FF     ;$A6 - (invalid)
	.BYTE      $FF     ;$A7 - CTRL-inverse
	.BYTE      $12     ;$A8 - CTRL-R
	.BYTE      $FF     ;$A9 - (invalid)
	.BYTE      $05     ;$AA - CTRL-E
	.BYTE      $19     ;$AB - CTRL-Y
	.BYTE      $09     ;$AC - CTRL-tab
	.BYTE      $14     ;$AD - CTRL-T
	.BYTE      $17     ;$AE - CTRL-W
	.BYTE      $11     ;$AF - CTRL-Q

	.BYTE      $FF     ;$B0 - CTRL-9 CUR_LMAR	(invalid)
	.BYTE      $FF     ;$B1 - (invalid)
	.BYTE      $FF     ;$B2 - CTRL-0 CUR_RMAR	(invalid)
	.BYTE      $FF     ;$B3 - CTRL-7 CUR_HOME	(invalid)
	.BYTE      $08     ;$B4 - CTRL-delete
	.BYTE      $FF     ;$B5 - CTRL-8 CUR_BOTTOM	(invalid)
	.BYTE      $FF     ;$B6 - CTRL-clear
	.BYTE      $FF     ;$B7 - CTRL-insert
	.BYTE      $06     ;$B8 - CTRL-F
	.BYTE      $08     ;$B9 - CTRL-H
	.BYTE      $04     ;$BA - CTRL-D
	.BYTE      $FF     ;$BB - (invalid)
	.BYTE      $FF     ;$BC - CTRL-CAPS
	.BYTE      $07     ;$BD - CTRL-G
	.BYTE      $13     ;$BE - CTRL-S
	.BYTE      $01     ;$BF - CTRL-A

**Comment by tschak909** [comment]
Thanks, Does the latest build do anything different?
-Thom

**Comment by mr-atari** [comment]
select t lets me back into tty and I can send at+cipsend to go into transparent mode.
so that is ok.

all other issues still stands.

any chance in getting the old graphic-routines back, perhaps only for testing?
some really annoying pixels/lines appear making it ugly to read.

again, if you need help coding in assembler, i can help.

**Comment by tschak909** [comment]
It makes no sense that you would be getting a double line feed...

As for the old routines, it will be difficult because the old routines used
a table that took up over 2.5K of space.

can you show me a picture of what you're seeing ?

-Thom

**Comment by tschak909** [comment]
(visually with the graphics, I mean)

**Comment by mr-atari** [comment]
Fire-up altirra (stock_800xl/rverter/2400baud all acceleration options disabled).
set/do " .traceser on"
run plato and just press enter.
you see it will send out cr/lf/lf

**Comment by mr-atari** [comment]
![all](https://user-images.githubusercontent.com/43779353/46579321-2a6e6c00-ca0f-11e8-9d67-50e30f8947a9.png)
This picture I posted earlier, crooked lines (old vs new).
No pictures of the other graphical issues, sorry.

**Comment by mr-atari** [comment]
Update:
On the real hardware (800xl/wifi), select t and select p does not work.
same, select T select P, no-go area. In the emulator I get a message below "mode xxx".
Now nothing happens, looking at the color feedback, plato is locked into in plato-mode.

So I connected before loading plato as I do/did before (using a terminal program).
Now something else is weird, the log-on screen loops and loops and loops.
when I type quickly guest/return a group is asked, but always invalid.
BACK brings me back to the log-on screen and it loops again.
See video.

Please ignore the color feedback, that is just a debug-function for my wifi to see data is coming.
[MOV08118.zip](https://github.com/tschak909/platoterm64/files/2453682/MOV08118.zip)

**Comment by mr-atari** [comment]
did exactly the same, with "plato-diet-fixed-keys" version.
so connected to irata.online, then loaded plato.
steady log-on screen, used guest and atari.
I am online at this moment.
Unfortunately, no use making pictures of the graphics/text, since this is the old engine....

Anyhow, now connected with 1200baud/256b buffer, lets play some checkers.... :-)

**Comment by mr-atari** [comment]
![dsc08119](https://user-images.githubusercontent.com/43779353/46579816-e41e0a80-ca18-11e8-93e5-1ee0e14dfe78.JPG)

**Comment by mr-atari** [comment]
20180915, some examples of graphical issues.
Extra dots, partial erased areas. Hoop this will help.

Beside that, nice to play around with plato as an alternative to "normal" billboarding :-)

Grtz,
Sijmen.

![dsc08120](https://user-images.githubusercontent.com/43779353/46579922-b89c1f80-ca1a-11e8-9e18-8f6d03dac33c.JPG)
![dsc08121](https://user-images.githubusercontent.com/43779353/46579923-b89c1f80-ca1a-11e8-8312-c70f4422ce7e.JPG)
![dsc08122](https://user-images.githubusercontent.com/43779353/46579924-b934b600-ca1a-11e8-82d7-ac9ca0636039.JPG)
![dsc08123](https://user-images.githubusercontent.com/43779353/46579925-b934b600-ca1a-11e8-9c84-f4f22b909180.JPG)
![dsc08124](https://user-images.githubusercontent.com/43779353/46579926-b934b600-ca1a-11e8-9bc5-54b3f0ee6d90.JPG)
![dsc08125](https://user-images.githubusercontent.com/43779353/46579927-b934b600-ca1a-11e8-8f19-72ef0e9cb211.JPG)
![dsc08126](https://user-images.githubusercontent.com/43779353/46579928-b9cd4c80-ca1a-11e8-952f-20f128c46ef2.JPG)
