### ISSUE TITLE
PLATOTerm64 locks up after filling 3D cuboid on main menu screen

### ISSUE THREAD

**Issue by cybern0id** [tschak909/platoterm64#20]
Hi Thom,

Firstly, what a cool project! I wish you every success and I'm really looking forward to becoming part of the PLATO community.

I've been trying PLATOTerm64 and after many failed attempts finally managed to connect; I didn't realise I needed to invert the modem make/break ratio pin with AT&P0 and enable hardware flow control with AT&K1 before connecting - adding this information to the documentation might be helpful!

However, PLATOTerm64 always locks up at the end of filling the cuboid image on the main menu. The mouse pointer still moves, just the terminal is unresponsive to keyboard input. The fill of the cuboid appears to go out of bounds just before it freezes - the last fill line shoots out diagonally left and down out of the cuboid to the other corner of the screen. The only way out is to reset the C64 - escaping the terminal with +++ doesn't work either. 

I will try to upload a screen capture later to show you what I mean. From your Youtube video, the point at which this happens on my setup is here: https://youtu.be/rmRMXSdsF-8?t=453

This hasn't happened on the other main menu images yet - neither Atari nor Tandy that I can remember though I haven't experimented with PLATOTerm64 extensively. 

Hardware:
UK PAL Commodore SX-64 and C64C
1541 Ultimate II floppy & cart emulator in expansion port
Wifi64 user-port wifi modem - 2400baud + AT&P0 + AT&K1
Wifi64 modem is this one: http://sharewareplus.blogspot.com/2018/01/commodore-64-wifi-modem-now-finished.html which I think is a "consumer" release of this one: https://blog.hpz.pw/commodore-64-wifi-modem/

Software:
PLATOTerm-1.0
Login as guest user and guest group/affiliation

Apologies for the rather wordy bug report.

**Comment by tschak909** [comment]
Ok, that means that fill is running out of stack space. I will expand the stack space for the C64 version, and see if this fixes the issue.

Thanks for the pointer to the documentation. I will be sure to add to both  the release notes, and motivate myself to finish the manual. (It is written in docbook, if you want to help, or know anyone who would want to help.)

-Thom

**Comment by tschak909** [comment]
I will be removing the fill, but it looks like there is a bug with user port modem support (the up2400 driver). Hopefully more to come..-Thom

**Comment by tschak909** [comment]
This has been fixed with the upcoming 1.1 release, a pre-release here:
https://github.com/tschak909/platoterm64/releases/download/PLATOTerm-1.0/PLATOTerm64-1_1-pre2.d64.d64
