### ISSUE TITLE
stdio.h File I/O adds 6K onto code.

### ISSUE THREAD

**Issue by tschak909** [tschak909/platoterm64#24]
I need to find a solution to the fact that when I add stdio.h, my code size balloons by 6K. I know I can use CIO on Atari, and there are the kernal routines in C64 and C128, am wondering, what I can do for apple2?

@groessler @greg-king5 am wondering what I should do? :)

-Thom

**Comment by groessler** [comment]
Did you find a solution?

**Comment by tschak909** [comment]
For now, just whiddling down (remove splash screen from code, replace tables with calcs). I managed to get the average size of all the targets to about 20K (I can do 16K carts if I pull out everything related to prefs and file i/o) I think the solution going forward is to strip out the preferences and config.

**Comment by tschak909** [comment]
right now, I am trying to get you guys a working plus 4 tgi driver. :) (It works, I just have to get the color RAM bits right)
