### ISSUE TITLE
[Atari] Handler spec for static-driver test?

### ISSUE THREAD

**Issue by jeffpiep** [tschak909/platoterm64#39]
Thom, is there an R: handler specification if I want to provide my own for the esp-cart? For example, where should the handler be located in RAM? Should the I/O buffers be located at a specific location? Thanks!

**Comment by tschak909** [comment]
Those are VERY good questions...

The best answer I can give, is to look at the existing code for the atrrdev serial driver:

git clone http://github.com/cc65/cc65.git

and look at:
https://github.com/cc65/cc65/blob/master/libsrc/atari/ser/atrrdev.s
https://github.com/cc65/cc65/tree/master/libsrc/serial

basically it's a set of functions to implement, and once implemented, a module can be produced that can either be statically built, OR built as a loadable module.

Let me know if I can help further.
And I..am _very_ interested in the esp cart :)

-Thom

**Comment by jeffpiep** [comment]
I have an R: handler written in MAC/65 that loads an AUTORUN.SYS file into $1D00. It is based on an R-Verter handler (AtariAge thread). It looks like the cc65 driver looks for the R: device and copies the jump table. The R:Verter and my adaptation don't have the same number of routines that CC65 is expecting. A comment at the head of the atrrdev.s file states "; RS232 routines using the R: device (currently tested with an 850 only)."

**Comment by tschak909** [comment]
If it's installing an R: handler, then the atrrdev.ser driver should work.

-Thom

**Comment by jeffpiep** [comment]
Hi Thom - I'm going to close this issue. I think the simplified R handler I wrote isn't 100% compliant to atrrdev.s . Thanks for the discussion.
