### ISSUE TITLE
Desperately Need faster text output

### ISSUE THREAD

**Issue by tschak909** [tschak909/platoterm64#4]
We need much faster text output, that takes the 6x5 font data in the character set, and transfers it to the display, but with transfer modes:

* Rewrite, black background, white foreground
* Inverse, white background, black foreground
* Erase, transparent background, black background
* Write, transparent background, white background

I can of course figure this all out on my own, and spend months doing so...would really like some help. 

-Thom

**Comment by dankreek** [comment]
I wouldn't mind helping out on this project. I've actually got a couple working C64's myself. May need a bit of help with the toolchain, however. I'm guessing this is all in gcc outputting 6502, but where does the `c64.h` header come from?

**Comment by tschak909** [comment]
This is done entirely in CC65, a cross compiling toolchain that outputs native 6502 code. It supports a huge chunk of modern C.

http://github.com/cc65/cc65

**Comment by dankreek** [comment]
Awesome! I'm finishing up a C64 joystick microcontroller project at the moment but I'll try and get a dev environment working on my machine and start playing around with this. Sounds fascinating!

**Comment by tschak909** [comment]
Thanks to Flashjazzcat (Jon Halliday), Atari now has this. Now need for Commodore and Apple. Will bifurcate for seperate targets and close this issue.
